[package]
name = "hello-autput"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example_wasm"
path = "src-rust/main.rs"

[dependencies]
autput = { path = "../../rust" }
log = "0.4.21"
